version: '3.9'

services:
  chatdb:
    container_name: chatdb
    environment:
        SA_PASSWORD: "YourStrong@Passw0rd"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  chat.api:
    container_name: chat.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:sqlConnection=Server=chatdb;Database=ChatDB;User Id=sa;Password=YourStrong@Passw0rd"            
        - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
        - chatdb
        - rabbitmq
    ports:
        - "8000:80"

  messagesender.api:
    container_name: messagesender.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
        - rabbitmq
    ports:
        - "8001:80"

  ui:
    ports:
      - "80:80"